# Heavily inspired from https://github.com/pybind/cmake_example/blob/master/.github/workflows/pip.yml
name: Test pyJanus

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.config.name }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        config:
          - { name: "Windows Latest MSVC", os: windows-latest }
          - { name: "Ubuntu Latest GCC", os: ubuntu-latest }
          - { name: "macOS Latest Clang", os: macos-latest }

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add requirements
        run: python -m pip install --upgrade wheel setuptools

      - name: Build and install
        run: pip install --verbose .[test]

      - name: Test
        run: python -m pytest --verbose
