name: pytest

on:
  workflow_dispatch:
  pull_request:
  push:
    # branches:
    #   - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8"]
        config:
          - { name: "Windows Latest", os: windows-latest }
          - { name: "Ubuntu Latest", os: ubuntu-latest }
          - { name: "macOS Latest", os: macos-latest }

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add requirements
        run: python -m pip install --upgrade wheel setuptools

      - name: Build and install
        run: pip install --verbose .[test]

      - name: Test
        run: python -m pytest
